services:
  productPGDatabase:
    image: postgres:12
    container_name: productPGDatabase
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product
    volumes:
      - ./data/product:/var/lib/postgresql/data

  OrderPGDatabase:
    image: postgres:12
    container_name: OrderPGDatabase
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order
    volumes:
      - ./data/order:/var/lib/postgresql/data